components/mpi-families/mvapich2/SPECS/mvapich2.spec
I've noticed that the ohpc builds of mvapich2 don't support RDMA CM. It is possible to enable it by adding a build dep on librdmacm-devel.
=> add a build dep on librdmacm-devel to enable RDMA CM support

README.md, docs/Release_Notes.txt
SuSE was renamed to SUSE a little bit more than 12 years ago,
its time to adjust.
=> Fix SUSE name

components/admin/lmod/SPECS/lmod.spec, components/admin/pdsh/SPECS/pdsh.spec, components/dev-tools/valgrind/SPECS/valgrind.spec, components/io-libs/hdf5/SPECS/hdf5.spec, components/io-libs/phdf5/SPECS/hdf5.spec, components/mpi-families/mvapich2/SOURCES/mvapich2-2.1-get_cycles-aarch64.patch, components/mpi-families/mvapich2/SPECS/mvapich2.spec, components/mpi-families/openmpi/SPECS/openmpi.spec, components/parallel-libs/hypre/SPECS/hypre.spec, components/parallel-libs/petsc/SPECS/petsc.spec, components/parallel-libs/trilinos/SOURCES/Trilinos-trilinos-aarch64.patch, components/parallel-libs/trilinos/SPECS/trilinos.spec, components/perf-tools/mpiP/SPECS/mpiP.spec, components/serial-libs/openblas/SOURCES/fix-arm64-cpuid-return.patch, components/serial-libs/openblas/SPECS/openblas.spec
With these patches, aarch64 on CentOS_7.2 builds 128 successful packages.  They are predominantly configuration fixes with a single patch against openblas to fix some bad code in the arm64 support.  I regressed them against x86_64 CentOS 7.2 and SuSe 12 SP 1 with no adverse effects on package builds.
Build test results against aarch64 available in my home project: https://build.openhpc.community/project/show/home:eric:OpenHPC:1.2:Factory
This is my first time really doing any sort of packaging work with Linux, I've mostly just stuck to code before, so be gentle.  Happy to take suggestions on ways of doing things better.
Signed-off-by: Eric Van Hensbergen <eric.vanhensbergen@arm.com>
=> aarch64: first batch of fixes

components/dev-tools/easybuild/SOURCES/bootstrap_eb.py-apply-patch.patch, components/dev-tools/easybuild/SPECS/easybuild.spec, components/perf-tools/tau/SPECS/tau.spec
Currently used easybuild fix fails silently to apply non-x86 patch causing false positive. This fix is less version dependent.
=> easybuild: update patch after version bump

components/dev-tools/easybuild/SOURCES/bootstrap_eb.py, components/dev-tools/easybuild/SPECS/easybuild.spec
@crbaird this should fix the offline installation issue we're hitting in #289
=> fix offline installation of EasyBuild

components/mpi-families/impi-devel/SPECS/intel-mpi.spec
This helps in case Intel MPI was installed on a shared file
system. See issue #254, that was fixed the same way.
=> use find -L to follow symlinks

components/perf-tools/mpiP/SOURCES/mpip.unwinder.patch, components/perf-tools/mpiP/SPECS/mpiP.spec
=> mpiP: AArch64 fix

components/rms/slurm/SPECS/slurm.spec
The plugin is built automatically if curl-config is found.
=> enable jobcomp_elasticsearch plugin in slurm

components/dev-tools/easybuild/SOURCES/bootstrap_eb.py, components/dev-tools/easybuild/SPECS/easybuild.spec
Although the updating the bootstrap script is not strictly required, it's worthwhile since it was enhanced a bit to have better sanity checking, cfr. https://github.com/hpcugent/easybuild-framework/pull/2199 (it would have helped in catching the problem we had a while ago with having `$EASYBUILD_VERSION` set).
=> EasyBuild v3.2.1

components/OHPC_macros
When building the OpenHPC packages outside of OBS some builds for
CentOS/RHEL are failing as the necessary macros are not available. This
sets the 'rhel_version' macro to 700 if the 'rhel' macro equals 7.
=> OHPC_macros: fix build outside of OBS

components/runtimes/singularity/SPECS/singularity.spec
The main reason for the changes was that the package was not building
without Source1: OHPC_macros outside of OBS.
Additionally:
* removed %%_rel macro as it is not used in OpenHPC
* removed unused definition of PNAME
* removed BuildRoot as it is automatically set by RPM
* moved building from the %%install to the %%build section
* replaced %%{?mflags_install} in %%install with
%%{?_smp_mflags} in %%build
* neither %%{?mflags} nor %%{?mflags_install} is defined
on CentOS:
* but %%{?_smp_mflags} is defined:
-j2
* removed %%clean section (automatically inserted by RPM)
=> singularity: few small fixes to singularity.spec

README.md, components/rms/slurm/SOURCES/rpmmacros, components/rms/slurm/SPECS/slurm.spec, misc/build_order.py, misc/build_order.sh
Building the OpenHPC packages outside of OBS in clean environment requires each time to manually decide in which order to build the packages. These scripts extract (Build)Requires of all spec files and try to resolve to correct order in which the OpenHPC packages should be built.
$ misc/build_order.sh
lua-filesystem.spec lua-bitop.spec sigar.spec luaposix.spec lmod.spec ohpc-filesystem.spec munge.spec [...]
=> build_order: resolve and print out the correct build order

docs/recipes/install/centos7/aarch64/warewulf/slurm/manifest/admin.tex, docs/recipes/install/centos7/aarch64/warewulf/slurm/manifest/dev-tools.tex, docs/recipes/install/centos7/aarch64/warewulf/slurm/manifest/patterns.tex, docs/recipes/install/centos7/aarch64/warewulf/slurm/manifest/rms.tex, docs/recipes/install/centos7/aarch64/warewulf/slurm/steps.tex, docs/recipes/install/sles12/aarch64/warewulf/slurm/manifest/admin.tex, docs/recipes/install/sles12/aarch64/warewulf/slurm/manifest/dev-tools.tex, docs/recipes/install/sles12/aarch64/warewulf/slurm/manifest/rms.tex, docs/recipes/install/sles12/aarch64/warewulf/slurm/steps.tex
I was browsing the Aarch64 install guide and noticed a few differences compared to x86:
1) The "Enable forwarding of system logs" section was in a different place.
2) The beegfs section was missing. It's possible this was intentional, however the rest of the aarch64 doc does reference beegfs throughout.
3) Some of the tables in the appendix "Package Manifest" were out of date. This was only for the tables without gnu7 references in them.
The document is also incorrect for 1.3.1 and 1.3 in the same ways, but it's probably too late to update now.
=> Update the install guide for Aarch64

components/dev-tools/scipy/SPECS/python-scipy.spec, components/perf-tools/imb/SOURCES/imb.cc.patch, components/perf-tools/imb/SPECS/imb.spec, components/serial-libs/scotch/SPECS/scotch.spec
This fixes a few broken builds on the 1.3.3 branch and does some minor
cleanups. Especially implicit defined or already defined parts from
OHPC_macros have been removed.
=> Various cleanups and build fixes

misc/get_source.sh
If building outside of OBS an automated way of getting all the
source tarballs is missing. Instead of manually downloading all
the required source archives this script tries to be clever
and downloads the source archives in the components SOURCES directory.
It only tries to download 'SourceX' lines with 'http' in them
and it also tries to handle URLs with '#[?]/' where the downloaded
source archive has another name then what rpmbuild is looking for.
It works like this:
$ misc/get_source.sh lmod.spec
./components/admin/lmod/SPECS/lmod.spec
Source0:   https://github.com/TACC/Lmod/archive/7.7.1.tar.gz#$/lmod-7.7.1.tar.gz
Trying to get https://github.com/TACC/Lmod/archive/7.7.1.tar.gz#$/lmod-7.7.1.tar.gz
https://github.com/TACC/Lmod/archive/7.7.1.tar.gz#$/lmod-7.7.1.tar.gz
Source1: …
=> get_source.sh: script which tries to download sources

misc/build_order.py, misc/build_order.sh
The build_order scripts are now skipping packages starting with
'kmod' and the RPM defines are now correct when running on Fedora.
=> misc/build_order: fix build_order scripts

docs/recipes/install/common/warewulf_chroot_customize_centos.tex, docs/recipes/install/common/warewulf_chroot_customize_sles.tex, docs/recipes/install/common/xcat_chroot_customize_centos.tex
- By not setting rsize/wsize, the client and server will autonegotiate
the maximum sizes, leading typically to the best performance.
- cto is the default NFS-standard conforming semantics so no need to
specify it explicitly.
- nodev,nosuid are for security. If /opt/ohpc/pub contains no suid
binaries, one could add nosuid to that mount as well.
- noatime is good for performance, and atime updates are typically
useless.
=> Update NFS mount options in docs

misc/build_order.sh, misc/build_srpm.sh, misc/get_source.sh, misc/shell-functions
The script build_srpm.sh builds a SRPM for specified packages. It
creates the necessary files in the SOURCES directory by either
downloading those files or creating symbolic links.
```
$ misc/build_srpm.sh lua
Building SRPM for ./components/distro-packages/lua-filesystem/SPECS/lua-filesystem.spec
/home/adrian/rpmbuild/SRPMS/lua-filesystem-ohpc-1.6.3-0.src.rpm
Building SRPM for ./components/distro-packages/lua-posix/SPECS/luaposix.spec
/home/adrian/rpmbuild/SRPMS/lua-posix-ohpc-33.2.1-1.ohpc.src.rpm
Building SRPM for ./components/distro-packages/lua-bit/SPECS/lua-bitop.spec
/home/adrian/rpmbuild/SRPMS/lua-bit-ohpc-1.0.2-1.ohpc.src.rpm
```
In combination with the build_order.sh script this can be used to create the OpenHPC SRPMs and rebuild them locally in the correct order.
=> add script to quickly build a SRPM

components/admin/pdsh/SPECS/pdsh.spec, components/compiler-families/llvm-compilers/SPECS/llvm-compilers.spec, components/dev-tools/autoconf/SPECS/autoconf.spec, components/io-libs/adios/SPECS/adios.spec, components/io-libs/hdf5/SPECS/hdf5.spec, components/io-libs/phdf5/SPECS/hdf5.spec, components/io-libs/pnetcdf/SPECS/pnetcdf.spec, components/mpi-families/openmpi/SPECS/openmpi.spec, components/parallel-libs/hypre/SPECS/hypre.spec, components/perf-tools/mpiP/SPECS/mpiP.spec, components/perf-tools/pdtoolkit/SPECS/pdtoolkit.spec, components/perf-tools/tau/SPECS/tau.spec, components/provisioning/warewulf-provision/SOURCES/warewulf-provision-ppc64le.patch, components/provisioning/warewulf-provision/SPECS/warewulf-provision.spec, components/serial-libs/openblas/SPECS/openblas.spec
With this all spec files have been adapted to also build on ppc64le.
Right now only llvm-compilers.spec does not build on ppc64le with:
llvm5-compilers-ohpc-5.0.0/llvm/projects/libunwind/include/__libunwind_config.h:55:4: error: #error "Unsupported architecture."
As this seems to be part of the actual source code and not packaging
related, and as nothing depends yet on llvm-compilers, llvm-compilers
has been ignored for the ppc64le effort.
This is also only compile tested but a first step towards ppc64le
support.
Test build results available at:
https://copr.fedorainfracloud.org/coprs/adrian/ohpc-ppc64le/packages/
=> Introduce ppc64le build-related options in .spec files

docs/recipes/install/centos7/input.local.template, docs/recipes/install/sles12/input.local.template
The input.local files were missing the opafm variable being defined. The recipe.sh script checks for these variables in order to install the opafm package and enable the service. Adding the variable to the input.local file will allow a user to select that parameter now for use.
=> Opafm variable in input.local

components/OHPC_macros, components/admin/ohpc-filesystem/SOURCES/ohpc-find-provides, components/admin/ohpc-filesystem/SOURCES/ohpc-find-requires, components/admin/ohpc-filesystem/SOURCES/ohpc.attr, components/admin/ohpc-filesystem/SPECS/ohpc-filesystem.spec
This includes several new files that are housed in `/usr/lib/rpm` to trigger the rpm dependency analysis plugin to use ohpc-provided scripts for analyzing ELF dependencies. These only get triggered for files installed into the `%{OHPC_HOME}` path.  This is one potential approach intended to avoid namespace collision with library .so's of the same name that might come from the underlying OS or other package repos (the example discussed in TSC meetings was `openblas`). 
In this approach, an additional color of `(ohpc)` is appended to relevant Provides and Requires dependencies if the .so is housed within `%{OHPC_HOME}`.
=> admin/ohpc-filesystem: include custom requires/provides plugin files for RPM dependency analysis

docs/recipes/install/common/add_to_compute_chroot_xcat_intro.tex
I'm adding the epel repo to the chroot. At least nagios needs it to fulfill the qstat and fping package dependencies. There may be other optional packages that require this as well which is why I'm not putting it into the nagios area only.
=> EPEL repo is required in the chroot for nagios plugins, fping and qstat (xCAT recipe).

components/rms/pbspro/SOURCES/rpmlintrc, components/rms/pbspro/SPECS/pbspro.spec
- Updating pbspro.spec to refer to 14.1.2 (latest open source version)
- Cleaned up variable name consistencies (pname vs pbs_name, etc)
- Altair move the location of the packages; change to Source0
- Altair agreed to create 'make dist' tar.gz, which OpenHPC will be relying on. No requirement to run autogen.sh
- Reduced verbosity by commenting out %postun and redirecting pbs_postinstall to /devnull
- Addressing the OBS Badness values. Nothing wrong with build.
=> Updating pbspro.spec for v14.1.2 and cleaning up misc

components/perf-tools/papi/SPECS/papi.spec
=> perf-tools/papi: bump version to v5.6.0 (#668)

components/dev-tools/python34-build-patch/SOURCES/unixccompiler.patch, components/dev-tools/python34-build-patch/SPECS/python34-build-patch.spec
A patch in the EPEL distribution of python3 (https://src.fedoraproject.org/rpms/python3/blob/master/f/00001-rpath.patch) causes numpy to fail at build time when using the Intel PSXE compilers on RHEL-like systems. This package contains a patch to revert that EPEL patch. Making this package a build requirement of numpy-intel-ohpc allows builds to complete successfully. 
=> initial import of python34-build-patch

components/OHPC_macros, components/rms/slurm/SPECS/slurm.spec
This PR adds the notion of a python family similar to our compiler and mpi families to allow a single spec file to produce multiple rpms for both python2.7 and python3.4. It defaults to python3, and a _link file in OBS can be used to use python2 as an alternative.
=> macros for OHPC-style builds of multiple python flavored packages from a single spec

components/io-libs/adios/SPECS/adios.spec
Since most of adios is not a python library, I split that off in to a separate sub-package
=> adios: use new ohpc python macros; add python sub-package (#654)(#627)

components/rms/munge/SPECS/munge.spec, components/rms/slurm/SPECS/slurm.spec
Resubmission of #642, see that discussion for additional information. 
Slurm and munge UID/GUIDs need to be consistent across the cluster. Munge already sets uid/guid of 200. This patch changes that to 201 (CentOS SYS_UID_MIN is 201) and sets slurm's to 202. 
xCAT stateful install has problems without this patch, because nodes and SMS end up with slurm ids being off by one, but this issue can come up in other contexts.
Signed-off-by: mhodak <mhodak@lenovo.com>
=> Consistent UIDs/GIDs for slurm and munge

components/perf-tools/geopm/SPECS/geopm.spec
We published a hotfix for a few issues.  This patch updates the spec file to point to version 0.5.1.
=> Update geopm to 0.5.1

docs/recipes/install/common/warewulf_chroot_customize_centos.tex, docs/recipes/install/common/warewulf_chroot_customize_sles.tex, docs/recipes/install/common/xcat_chroot_customize_centos.tex, docs/recipes/install/common/xcat_stateful_customize_centos.tex
In commit 67141e1 I, among other things, added noatime to the NFS
mount options. However, it turns out that the Linux NFS client, in
fact, ignores any atime related mount options, and instead
unconditionally implements its own relaxed atime semantics. For more
details, see http://man7.org/linux/man-pages/man5/nfs.5.html .
Signed-off-by: Janne Blomqvist <janne.blomqvist@aalto.fi>
=> Remove noatime from NFS mount options

components/io-libs/adios/SPECS/adios.spec, misc/build_order.sh
The build_order script stumbled about an unversioned python dependency in adios. This tries to fix this.
=> Fix adios python dependencies and build_order script

components/dev-tools/easybuild/SPECS/easybuild.spec
Reverts openhpc/ohpc#796
will land again on obs/OpenHPC_1.3.6_Factory
=> Revert " EasyBuild v3.6.2"

components/OHPC_macros
This sets the disttag to the current branch name. This replicates OBS's
behavior to append the current release string to the release.
Currently this is ".ohpc.1.3.6"
=> OHPC_macros: set disttag to current branch name

.travis.yml, tests/travis/.gitignore, tests/travis/Dockerfile.check_spec, tests/travis/check_spec.py
Our initial travis test is a small python script which only looks at the
SPEC files of the pull request and checks if they include any lines we
do not need. Currently this includes:
* '^Source999.*$' (That is reserved for OHPC_macros)
* '^Source.*OHPC_macros$' (That is not necessary anymore)
* '^%changelog.*' (We removed all changelogs)
* '^DocDir.*' (Set by OHPC_macros)
* '^BuildRoot.*' (Not necessary anymore)
* '^%defattr\(-,root,root\).*' (Setting the default value is not necessary)
With this initial travis setup running we can easily include more and
more checks in the future.
=> travis: configure travis

components/rms/slurm/SPECS/slurm.spec
This is needed for SLURM's NUMA affinity features to work.
Signed-off-by: Kevin Pedretti <ktpedre@sandia.gov>
=> Build SLURM with numa and hwloc support.

components/OHPC_macros
.so's that are shipped with the compiler or performance
libraries. Until this is fixed, instruct rpmbuild to skip listing key
.so's provided by the compiler toolchain as formal Requires for ohpc
builds.
=> arm hpc RPM packages do not currently enable Provides metadata for

components/OHPC_compiler_deps, components/OHPC_macros, components/OHPC_setup_compiler, components/compiler-families/gnu-compilers/SPECS/gnu-compilers.spec
The work to use the devtoolset based compiler for OpenHPC on CentOS does
not need to be part of the repository if it is unused. If necessary it
can be brought back from git any time.
=> compilers: remove dts conditionals

components/dev-tools/cmake/LICENSE, components/dev-tools/cmake/SPECS/cmake.spec
3.12 addressed an important bug introduced into 3.11 that causes the Intel C compiler to not be able to properly use -std=gnu11 and instead always use -std=c11, which forces ANSI C compatibility and breaks POSIX functionality.
=> CMake: Bump to 3.12.1 and use more system libraries as dependencies

components/parallel-libs/scalapack/SPECS/scalapack.spec
This 'if' expression in modulefile did not work on any of my CentOS7 machines; repaced with something that actually works.
=> scalapack: reworked 'if' expression

components/perf-tools/msr-safe/SOURCES/0001-Correcting-hash_for_each_possible-function.-Fixes-41.patch, components/perf-tools/msr-safe/SOURCES/0002-Adding-slurm-spank-plugin-to-enable-MSR-save-restore.patch, components/perf-tools/msr-safe/SPECS/msr-safe.spec
- Include patch from msr-safe mainline that came in before
the spank plugin as well.
Signed-off-by: Christopher M. Cantalupo <christopher.m.cantalupo@intel.com>
=> Add spank plugin to msr-safe to enable save/restore for jobs.

components/perf-tools/geopm/SPECS/geopm.spec, components/perf-tools/msr-safe/SPECS/msr-safe.spec
- Was msr-safe-ohpc-slurm => msr-safe-slurm-ohpc
- Also add dependency from geopm to the msr-safe slurm plugin.
Signed-off-by: Christopher M. Cantalupo <christopher.m.cantalupo@intel.com>
=> Modify msr-safe spank plugin RPM name.

components/admin/meta-packages/SPECS/meta-packages.spec, components/perf-tools/geopm/SPECS/geopm.spec, components/perf-tools/msr-safe/SPECS/msr-safe.spec, components/rms/slurm/SPECS/slurm.spec, docs/recipes/install/common/add_ww_hosts_finalize.tex, docs/recipes/install/common/add_ww_hosts_intro.tex, docs/recipes/install/common/charliecloud_centos_warewulf_post.tex, docs/recipes/install/common/conman_post.tex, docs/recipes/install/common/geopm.tex
- Disable intel_pstate kernel driver via the kernel cmdline.
- Enable SLURM's task/affinity plugin for per rank CPU pinning.
Signed-off-by: Brad Geltz <brad.geltz@intel.com>
=> Update config files per GEOPM requirements.

components/runtimes/singularity/SPECS/singularity.spec
Increment Singularity package version to 2.6.0 to avoid environment variables bugs.
Also modified URL to point to the new Singularity organisation (Sylabs rather than Singularityware).
Signed-off-by: Chris <chrisdowning250@gmail.com>
=> Updated Singularity to 2.6.0

components/admin/clustershell/SPECS/clustershell.spec, components/admin/lmod/SPECS/lmod.spec, components/admin/mrsh/SPECS/mrsh.spec, components/admin/ndoutils/SPECS/ndoutils.spec, components/admin/nrpe/SPECS/nrpe.spec, components/admin/powerman/SPECS/powerman.spec, components/distro-packages/ipmiutil/SPECS/ipmiutil.spec, components/mpi-families/mvapich2/SPECS/mvapich2.spec, components/mpi-families/openmpi/SPECS/openmpi.spec, components/parallel-libs/trilinos/SPECS/trilinos.spec, components/perf-tools/dimemas/SPECS/dimemas.spec, components/perf-tools/extrae/SPECS/extrae.spec, components/perf-tools/geopm/SPECS/geopm.spec, components/perf-tools/pdtoolkit/SPECS/pdtoolkit.spec, components/perf-tools/scalasca/SPECS/scalasca.spec, components/perf-tools/tau/SPECS/tau.spec, components/provisioning/warewulf-common/SPECS/warewulf-common.spec, components/provisioning/warewulf-ipmi/SPECS/warewulf-ipmi.spec, components/runtimes/charliecloud/SPECS/charliecloud.spec, components/serial-libs/scotch/SPECS/scotch.spec
This mainly removes conditionals from SPEC files for distributions (EL5, EL6, Fedora) which OpenHPC does not support. It also cleans up trailing whitespace and commented out lines.
=> SPEC file cleanups

components/rms/pbspro/SPECS/pbspro.spec
changes to buildrequires for postgres
=> rms/pbspro: remove centos7.6 patch landed on latest version; revert

components/rms/munge/SOURCES/munge.syslog.patch, components/rms/munge/SPECS/munge.spec
By default munge writes logs by itself to
/var/long/munge/munged.log. This prevents those logs from being
forwarded to the log server (e.g. the OpenHPC SMS/admin machine), and
in case those logs for one reason or another grows rapidly (e.g.
https://github.com/dun/munge/issues/26) it can be a problem for
diskless nodes or compute nodes with small partitions for /var/log.
This should fix https://github.com/openhpc/ohpc/issues/943
Signed-off-by: Janne Blomqvist <janne.blomqvist@aalto.fi>
=> Make munged log via syslog

components/runtimes/singularity/SPECS/singularity.spec
According to #951 OpenHPC's singularity package had wrong file
permissions for certain files. This adapts the file permissions as seen
in the upstream spec file.
=> singularity: fix file permissions

components/parallel-libs/boost/SOURCES/boost-1.66.0-bjam-build-flags.patch, components/parallel-libs/boost/SOURCES/boost-1.66.0-build-optflags.patch, components/parallel-libs/boost/SPECS/boost.spec
This includes a patch to pickup the default optimization flags from the OS to build boost.
It also changes the output during the compile to print the actual compiler invocation to see in the build logs which compiler flags have been used.
Fixes: #971
=> Update boost to 1.70.0

tests/perf-tools/geopm/tests/lscpu.sh
- Name of lscpu cache file has changed from "/tmp/geopm-lscpu.log" to
"/tmp/geopm-topo-cache".
Signed-off-by: Christopher M. Cantalupo <christopher.m.cantalupo@intel.com>
=> Update lscpu call to use "geopmread --cache" in GEOPM tests

tests/travis/check_spec.py
I noticed with #1005 that Travis was attempting to check a deleted spec file to ensure that it had the required spec file components.  I don't think this is the desired behavior.  This PR should filter out deleted items from being checked if the version of `git` being used is less than 1.8.5.  From what I can tell, travis is using a CentOS 7 docker image which is git version 1.8.3.
```
$ git --version
git version 1.8.3.1
$ grep filter tests/travis/check_spec.py
command = ['git', 'diff', '--diff-filter=ACMRTUXB', '--name-only', sys.argv[1]]
$ tests/travis/check_spec.py 90ebc7959bb698545959a2e1e4c0f8e21211d197...36214738481f5189a665d66e699040d1e2ae6ef7
About to run command git diff --diff-filter=ACMRTUXB --name-only 90ebc7959bb698545959a2e1e4c0f8e21211d197...36214738481f5189a665d66e699040d1e …
```
=> Do not check that deleted spec files conform to project guidelines

components/mpi-families/mpich/SOURCES/node.name.fix.patch
Adding patch file fixing mpich issue where jobs fail if some nodes do not end with a number. From pmodels/mpich#3947
=> Add node name patch file for mpich

components/admin/nagios-plugins/SPECS/nagios-plugins.spec, components/admin/nagios/SPECS/nagios.spec, components/admin/ndoutils/SPECS/ndoutils.spec, components/admin/nrpe/SPECS/nrpe.spec
Most of the other specfiles already implement the BuildIgnores comment. The remaining four use an invalid RPM syntax, so these packages cannot be compiled outside of OBS without correcting them first.
=> Update post-build-check ignore macro

tests/travis/Dockerfile.check_spec
In #1032 travis is failing because the `python36` command is not found.  It looks like EPEL has deprecated this package in favor of the CentOS 7.7 provided one[1].
Because the default python3 is the appropriate version already and because the shebang in `check_spec.py` already calls out the less specific python version, I think it's appropriate that the Dockerfile be updated to match.
_edited to reflect the package was deprecated not renamed_
[1] https://lists.fedoraproject.org/archives/list/epel-devel@lists.fedoraproject.org/thread/GUSLTD5AJWFEGBFK5EYFVH3LHQVHUBAP/#AT736IKJUKNLP55YQETEFN2YJ5GM2YWO
=> Use less specific python version for travis

components/parallel-libs/boost/SOURCES/boost-1.71.0-intel-bootstrap.patch, components/parallel-libs/boost/SPECS/boost.spec
The boost `intel-linux` toolset has an issue[1] open regarding the missing `-std=c++11` for the intel compiler.  I've added a patch that implements the suggested fix from that issue.  I ran the boost ohpc test suite and the non resource manager based tests seem to be passing.  I haven't run the resource manager based tests as my local environment isn't yet set up for that.
Should fix #1035
[1] https://github.com/boostorg/build/issues/475
=> Patch intel-linux toolset to use -std=c++11 

misc/dist/README.in
This patch corrected the 'ls' command output in README of
OpenHPC-@VERSION@.@DISTRO@.@ARCH@.tar.
=> Fixed 'ls' output in README for creating OHPC local repo

components/parallel-libs/hypre/SPECS/hypre.spec
* hypre changed its license from LGPL-2.1 to Apache-2.0/MIT
* the fei-base directory is no longer part of hypre (it used to be
copied to include/FEI_mv/
Fixes: #1065
=> hypre: Upgrade to to 2.18.1

components/perf-tools/msr-safe/SPECS/msr-safe.spec
Add a patch on top of 1.3.0 from the master branch which fixes save restore for MSRs with open write masks.  This should be applied instead of #1008.  @bgeltz can you take that PR down?  Thanks.
relates to #1008
=> Updates msr-safe to version 1.4.0

tests/libs/opencoarrays/configure.ac, tests/libs/opencoarrays/tests/rm_execution
In #884 it was determined that the `caf` wrapper script was broken.  According to the [documentation](https://github.com/sourceryinstitute/OpenCoarrays/blob/master/GETTING_STARTED.md) this wrapper is the preferred method for using opencoarrays.  In order to ensure that this script is working going forward, this PR modifies the existing opencoarrays tests to use `caf` instead of calling `mpif*` directly.  Additionally, it adds another resource manager test to ensure that `cafrun` runs MPI jobs as expected.
When I tested this on OpenHPC 1.3.8.1 the tests fail with an expected error[1] as described in #884.  With the current 1.3.9 that's staged, these tests pass for openmpi3 and mpich.  I'm seeing failures for mvapich2 but I believe that's a known issue.
[1]
```
configure:1921: checking for …
```
=> Use caf and cafrun wrappers for opencoarrays tests

components/rms/pmix/SPECS/pmix.spec
* remove BR on lmod and libtool as it is unused
* update to 2.2.3
* switch Source to Source0 (newer RPMs require that)
Same PR as on the 1.3.9 branch
=> pmix: remove unnecessary BuildRequires
