openhpc/ohpc

- components/dev-tools/easybuild/SPECS/easybuild.spec
- components/dev-tools/numpy/SOURCES/numpy-intelccomp.patch
- components/dev-tools/numpy/SOURCES/numpy-intelfcomp.patch
- components/dev-tools/numpy/SPECS/python-numpy.spec
- components/parallel-libs/superlu_dist/SPECS/superlu_dist.spec
- components/perf-tools/pdtoolkit/SPECS/pdtoolkit.spec
- components/provisioning/warewulf-common/SPECS/warewulf-common.spec
- components/provisioning/warewulf-ipmi/SOURCES/warewulf-ipmi-3.6-config_guess.patch
- components/provisioning/warewulf-provision/SOURCES/warewulf-provision.config_guess.patch
- components/provisioning/warewulf-vnfs/SPECS/warewulf-vnfs.spec
- tests/admin/nagios
> warewulf: copy config.sub too

- components/parallel-libs/hypre/SPECS/hypre.spec
> Hypre: copy config.guess for AArch64

- tests/libs/openblas/tests/c_c3chke.c
- tests/libs/openblas/tests/c_cblas3.c
- tests/libs/openblas/tests/c_z3chke.c
- tests/libs/openblas/tests/c_zblas3.c
> Tests: OpenBLAS: AArch64 tweaks

- docs/recipes/install/centos7.2/aarch64/warewulf/slurm/manifest/pkg-ohpc.admin
- docs/recipes/install/centos7.2/aarch64/warewulf/slurm/manifest/pkg-ohpc.all
- docs/recipes/install/centos7.2/aarch64/warewulf/slurm/manifest/pkg-ohpc.compiler-families
- docs/recipes/install/centos7.2/aarch64/warewulf/slurm/manifest/pkg-ohpc.dev-tools
- docs/recipes/install/centos7.2/aarch64/warewulf/slurm/manifest/pkg-ohpc.distro-packages
- docs/recipes/install/centos7.2/aarch64/warewulf/slurm/manifest/pkg-ohpc.io-libs
- docs/recipes/install/centos7.2/aarch64/warewulf/slurm/manifest/pkg-ohpc.lustre
- docs/recipes/install/centos7.2/aarch64/warewulf/slurm/manifest/pkg-ohpc.mpi-families
- docs/recipes/install/centos7.2/aarch64/warewulf/slurm/manifest/pkg-ohpc.parallel-libs
- docs/recipes/install/centos7.2/aarch64/warewulf/slurm/manifest/pkg-ohpc.perf-tools
- docs/recipes/install/centos7.2/aarch64/warewulf/slurm/manifest/pkg-ohpc.provisioning
- docs/recipes/install/centos7.2/aarch64/warewulf/slurm/manifest/pkg-ohpc.rms
- docs/recipes/install/centos7.2/aarch64/warewulf/slurm/manifest/pkg-ohpc.runtimes
- docs/recipes/install/centos7.2/aarch64/warewulf/slurm/manifest/pkg-ohpc.serial-libs
Signed-off-by: Eric Van Hensbergen <ericvh@gmail.com>
> docs: Add manifest for aarch64 CentOS-7.2 warewulf/slurm configuration

- components/dev-tools/easybuild/SPECS/easybuild.spec
(WIP because I haven't checked whether this passes the integration tests)
> EasyBuild v3.1.1 (WIP)

- components/dev-tools/valgrind/SOURCES/aarch64_always_use_fallback_LLSC.patch
- components/dev-tools/valgrind/SOURCES/rev16269.patch
- components/dev-tools/valgrind/SOURCES/rev16309.patch
- components/dev-tools/valgrind/SOURCES/revVEX3352.patch
- components/dev-tools/valgrind/SPECS/valgrind.spec
This is to fix following issue: https://bugs.kde.org/show_bug.cgi?id=369459
> valgrind: AArch64 fix (imported from Valgrind SVN)

- components/parallel-libs/plasma/LICENSE
- components/parallel-libs/plasma/SOURCES/plasma-rpmlintrc
- components/parallel-libs/plasma/SOURCES/plasma-sharedlibs-2.8.0.patch
- components/parallel-libs/plasma/SPECS/plasma.spec
Initiating PR for PLASMA based on initial work by @takekato (#469).
> Plasma addition

- components/admin/nagios/SPECS/nagios.spec
Building the nagios package outside of OBS failed as it was missing the
BR on systemd. This adds the necessary BuildRequires and cleaned up the
nagios spec file a bit:
* removed setting PROJ_DELIM as it comes from OHPC_macros
* removed setting PNAME as it is not used
* removed BuildRoot - automatically defined by RPM
* fixed systemd Requires and BuildRequires
* removed German summary as no other package has localized summaries
* removed trailing whitespaces
* removed cleaning of buildroot - done by RPM
* use predefined systemd macros for service control in preun/post/postun
> nagios: fix building on RHEL/CentOS

- components/OHPC_macros
- components/compiler-families/gnu-compilers/SPECS/gnu-compilers.spec
- components/compiler-families/llvm-compilers/SPECS/llvm-compilers.spec
> gcc: update to 7.2.0

- components/admin/meta-packages/SOURCES/LICENSE
- components/admin/meta-packages/SPECS/meta-packages.spec
- components/admin/prun/SOURCES/LICENSE
- components/dev-tools/scipy/SPECS/python-scipy.spec
- components/runtimes/ocr/SPECS/ocr.spec
> fix building prun and meta-packages due to missing files

- components/admin/clustershell/SPECS/clustershell.spec
- components/admin/lmod/SPECS/lmod.spec
- components/admin/losf/SPECS/losf.spec
- components/admin/mrsh/SPECS/mrsh.spec
- components/admin/pdsh/SPECS/pdsh.spec
- components/admin/powerman/SPECS/powerman.spec
- components/admin/prun/SPECS/prun.spec
- components/dev-tools/autoconf/SPECS/autoconf.spec
- components/dev-tools/automake/SPECS/automake.spec
- components/dev-tools/easybuild/SPECS/easybuild.spec
- components/dev-tools/libtool/SPECS/libtool.spec
- components/dev-tools/valgrind/SPECS/valgrind.spec
- components/distro-packages/python-Cython/SPECS/python-Cython.spec
- components/parallel-libs/scotch/SPECS/ptscotch.spec
- components/perf-tools/papi/SPECS/papi.spec
- components/rms/pbspro/SPECS/pbspro.spec
- components/serial-libs/plasma/SPECS/plasma.spec
> This adds a dist-tag for everyone

- docs/recipes/install/centos7/x86_64/warewulf/pbspro/steps.tex
- docs/recipes/install/centos7/x86_64/warewulf/slurm/steps.tex
- docs/recipes/install/centos7/x86_64/xcat/slurm/steps.tex
- docs/recipes/install/common/compute_customizations_intro.tex
- docs/recipes/install/common/ohpc-doc.sty
- docs/recipes/install/common/sensys.tex
- docs/recipes/install/sles12/x86_64/warewulf/pbspro/steps.tex
- docs/recipes/install/sles12/x86_64/warewulf/slurm/steps.tex
- docs/recipes/install/sles12/x86_64/xcat/slurm/steps.tex
Signed-off-by: Marcela Morales Quispe <marcela.morales.quispe@intel.com>
> Added Sensys monitoring documentation.

- tests/admin/Makefile.am
- tests/admin/sensys
Signed-off-by: Gustavo Martinez Bernal <gustavo.martinez.bernal@intel.com>
> Sesnys Test Added

- Singularity.1.3.3.el7
- components/perf-tools/tau/SOURCES/tau-ucontext.patch
- components/perf-tools/tau/SPECS/tau.spec
- docs/recipes/install/common/stateful.tex
- docs/recipes/install/sles12/aarch64/warewulf/slurm/steps.tex
See also 
https://sourceware.org/git/gitweb.cgi?p=glibc.git;a=commitdiff;h=251287734e89a52da3db682a8241eb6bccc050c9;hp=c86ed71d633c22d6f638576f7660c52a5f783d66
> ucontext not supportet by newer glibc version

- components/rms/pbspro/SPECS/pbspro.spec
updating version of pbspro.spec file to latest 14.1.2; verified that source URL.
> #631 updating version of pbspro.spec file to latest 14.1.2

- components/admin/nhc/SPECS/nhc.spec
> initial import of NHC (#666)

- components/rms/slurm/SPECS/slurm.spec
A user on the mailing list requested sview.
> rms/slurm: require gtk2 to trigger build of sview (#605)

- README.md
- components/perf-tools/dimemas/SPECS/dimemas.spec
- components/perf-tools/extrae/SPECS/extrae.spec
- components/perf-tools/paraver/SPECS/wxparaver.spec
Signed-off-by: Juan Valls <juan.valls@bsc.es>
> Add dimemas, extrae and paraver spec files

- components/compiler-families/intel-compilers-devel/SPECS/intel-compilers-devel.spec
ohpc-style modulefiles during package upgrade (#718)
> compiler-families/intel-compilers-devel: fix for erroneous removal of

- components/dev-tools/easybuild/SOURCES/bootstrap_eb.py
- components/dev-tools/easybuild/SPECS/easybuild.spec
updated bootstrap script deals with some changes that were made to PyPI
> EasyBuild v3.6.0 + updated bootstrap script

- components/parallel-libs/fftw/SPECS/fftw.spec
Updated fftw to 3.3.8 (#774) and a few small SPEC file cleanups.
> Update fftw to 3.3.8

- components/parallel-libs/fftw/SPECS/fftw.spec
With this change fftw is now built three times. For single, double, and
long double precision. This does not yet enable quad precision as quad
precision does not support building with MPI support.
This commit also enable '--enable-neon' for aarch64 builds.
> fftw: also build single and long double precision

- components/OHPC_macros
- components/OHPC_setup_compiler
- components/compiler-families/arm-compilers-devel/SPECS/arm-compilers-devel.spec
work towards arm-hpc family builds (#685)
> add compatibility package for arm-hpc compilers

- components/admin/lmod/SPECS/lmod.spec
> admin/lmod: bump version to v7.7.39 (#811)

- components/admin/pdsh/SPECS/pdsh.spec
- docs/recipes/install/centos7/aarch64/warewulf/slurm/manifest/admin.tex
- docs/recipes/install/centos7/aarch64/warewulf/slurm/manifest/pkg-ohpc.admin
- docs/recipes/install/centos7/aarch64/warewulf/slurm/manifest/pkg-ohpc.all
- docs/recipes/install/centos7/x86_64/warewulf/slurm/manifest/admin.tex
- docs/recipes/install/centos7/x86_64/warewulf/slurm/manifest/pkg-ohpc.admin
- docs/recipes/install/centos7/x86_64/warewulf/slurm/manifest/pkg-ohpc.all
- docs/recipes/install/common/build_tables.pl
- docs/recipes/install/common/component_list.pl
- docs/recipes/install/sles12/aarch64/warewulf/slurm/manifest/admin.tex
- docs/recipes/install/sles12/aarch64/warewulf/slurm/manifest/pkg-ohpc.admin
- docs/recipes/install/sles12/aarch64/warewulf/slurm/manifest/pkg-ohpc.all
- docs/recipes/install/sles12/x86_64/warewulf/slurm/manifest/admin.tex
- docs/recipes/install/sles12/x86_64/warewulf/slurm/manifest/pkg-ohpc.admin
- docs/recipes/install/sles12/x86_64/warewulf/slurm/manifest/pkg-ohpc.all
Signed-off-by: Janne Blomqvist <janne.blomqvist@aalto.fi>
> Update pdsh project URL

- components/serial-libs/R/SPECS/R.spec
Link R against ArmPL library (OpenMP flavour)
> arm compiler: R quirks

- components/perf-tools/msr-safe/SOURCES/10-msr-safe.rules
- tests/perf-tools/geopm/tests/lscpu.sh
- tests/perf-tools/geopm/tests/rm_execution
- tests/perf-tools/geopm/tests/test_module
Signed-off-by: Brad Geltz <brad.geltz@intel.com>
> Fix failing unit tests for GEOPM.

- components/rms/pbspro/SPECS/pbspro.spec
> rms/pbspro: updating version to v18.1.3

- components/perf-tools/geopm/SPECS/geopm.spec
We just released v0.6.1 which contains some bug fixes for v0.6.0.
> Update geopm to v0.6.1

- components/dev-tools/easybuild/SOURCES/bootstrap_eb.py
- components/dev-tools/easybuild/SPECS/easybuild.spec
EasyBuild v3.7.1 was released last week
> Easybuild 3.7.1 + update EasyBuild bootstrap script to latest version

- components/admin/ohpc-filesystem/SOURCES/ohpc-find-requires
Signed-off-by: Götz Waschk <goetz.waschk@desy.de>
> fix error printing in case no search path was provided

- components/dev-tools/spack/SPECS/spack.spec
> Update spack to 0.12.1

- components/perf-tools/scorep/SPECS/scorep.spec
> scorep: updated to 4.1

- components/parallel-libs/superlu_dist/SOURCES/superlu_dist-make.inc
- components/parallel-libs/superlu_dist/SPECS/superlu_dist.spec
> superlu_dist: upgraded to 6.1.1

- components/parallel-libs/slepc/SPECS/slepc.spec
> slepc: upgraded slepc to 3.10.2

- components/parallel-libs/hypre/SPECS/hypre.spec
> Hypre update and cleanup

- components/parallel-libs/boost/SPECS/boost.spec
> Upgrade boost to 1.69.0

- components/parallel-libs/boost/SOURCES/boost-1.69-mpi-c_data.patch
- components/parallel-libs/boost/SPECS/boost.spec
As discussed: a patch to fix possible errors when using MPI.
> boost: fix for MPI related errors

- components/rms/pbspro/SOURCES/pbspro-centos-7.6-ical.patch
- components/rms/pbspro/SPECS/pbspro.spec
Patch taken from https://github.com/PBSPro/pbspro/pull/910
> Fix pbspro build failure on Centos 7.6

- components/rms/pbspro/SPECS/pbspro.spec
Bring the OHPC spec file for PBS Pro closer to the one packaged with PBS and update the version to 19.1.1.
> Update PBS Pro to version 19.1.1

- components/dev-tools/easybuild/SOURCES/bootstrap_eb.py
- components/dev-tools/easybuild/SPECS/easybuild.spec
https://pypi.org/project/easybuild/3.9.0
> EasyBuild v3.9.0 

- components/parallel-libs/petsc/SPECS/petsc.spec
> petsc: Upgrade petsc tp 3.11.1

- components/serial-libs/plasma/SPECS/plasma.spec
This is real big update. The plasma build-system is completely different
now. This change includes running 'plasmatest' during %check to
verify that this newly build plasma does what it is supposed to do.
> plasma: Update to 18.11.1

- components/dev-tools/easybuild/SPECS/easybuild.spec
https://pypi.org/project/easybuild
> EasyBuild 3.9.1

- components/perf-tools/scorep/SPECS/scorep.spec
Use base OS compiler optimization flags.
> scorep: Update to 5.0

- components/perf-tools/geopm/SPECS/geopm.spec
Signed-off-by: Christopher M. Cantalupo <christopher.m.cantalupo@intel.com>
> Update geopm to version 1.0

- components/mpi-families/mpich/SPECS/mpich.spec
> Apply patch to fix node name issue in mpich

- components/dev-tools/easybuild/SPECS/easybuild.spec
https://pypi.org/project/easybuild/3.9.3/
> EasyBuild 3.9.4
